"""empty message

Revision ID: 904aae454014
Revises: 0295c6747189
Create Date: 2023-04-06 13:59:34.301530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904aae454014'
down_revision = '0295c6747189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
